from xml.sax.saxutils import escape as xml_escape
from langchain_core.messages import BaseMessage
from langchain_core.language_models import BaseChatModel
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from pydantic import BaseModel, Field


class Commit(BaseModel):
    message: str = Field(..., description="The commit message generated by the AI.")


class AI:
    def __init__(self, model: BaseChatModel):
        self.model = model

    def generate_commit_message(
        self, recent_logs: list[str], diff: str, history: list[BaseMessage]
    ) -> str:
        prompt_template = ChatPromptTemplate.from_messages(
            [
                (
                    "system",
                    "<persona>You are a seasoned software engineer and Git expert who writes precise commit messages.</persona>\n"
                    + "<objectives>\n"
                    + "  <objective>Study the provided diff to understand what changed and why.</objective>\n"
                    + "  <objective>Return a single well-crafted commit message.</objective>\n"
                    + "</objectives>\n"
                    + "<guidelines>\n"
                    + "  <guideline>Mirror the style conventions observed in the recent logs. (e.g. tense, tags, emoji, prefixes)</guideline>\n"
                    + "  <guideline>Add one or two short follow-up lines when necessary to clarify scope or motivation; use bullet points for multiple discrete changes, or paragraph style for single coherent explanations. Each line should stay under 72 characters.</guideline>\n"
                    + "</guidelines>",
                ),
                ("human", "<recent-logs>{logs}</recent-logs><diff>{diff}</diff>"),
                MessagesPlaceholder("history"),
            ]
        )
        chain = prompt_template | self.model.with_structured_output(Commit)

        commit: Commit = chain.invoke(
            {
                "logs": "\n".join(
                    f"<log>{xml_escape(log)}</log>" for log in recent_logs
                ),
                "diff": xml_escape(diff),
                "history": history,
            }
        )  # type: ignore
        return commit.message
