from xml.sax.saxutils import escape as xml_escape
from langchain_core.messages import BaseMessage
from langchain_core.language_models import BaseChatModel
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from pydantic import BaseModel, Field


class Commit(BaseModel):
    message: str = Field(..., description="The commit message generated by the AI.")


class AI:
    def __init__(self, model: BaseChatModel):
        self.model = model

    def generate_commit_message(
        self, recent_logs: list[str], diff: str, history: list[BaseMessage]
    ) -> str:
        prompt_template = ChatPromptTemplate.from_messages(
            [
                (
                    "system",
                    "<role>You are an excellent software engineer.</role>\n"
                    + "<task>Generate an appropriate commit message based on the provided diff and recent commit logs from the user.</task>",
                ),
                ("human", "<recent-logs>{logs}</recent-logs><diff>{diff}</diff>"),
                MessagesPlaceholder("history"),
            ]
        )
        chain = prompt_template | self.model.with_structured_output(Commit)

        commit: Commit = chain.invoke(
            {
                "logs": "\n".join(
                    f"<log>{xml_escape(log)}</log>" for log in recent_logs
                ),
                "diff": xml_escape(diff),
                "history": history,
            }
        )  # type: ignore
        return commit.message
